# Generated by Django 6.1.1 on 2026-09-14 01:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('CRM', models.CharField(max_length=20, unique=True, verbose_name='CRM')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10, verbose_name='Gênero')),
                ('expertise', models.CharField(max_length=100, verbose_name='Especialidade')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Classificação')),
                ('place', models.CharField(max_length=100, verbose_name='Local da Consulta')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço da Consulta')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('CPF', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10, verbose_name='Gênero')),
                ('health_insurance', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data da Consulta')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.doctor', verbose_name='Médico')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.pacient', verbose_name='Paciente')),
            ],
        ),
    ]
