# Generated by Django 6.1.1 on 2026-09-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['CRM']},
        ),
        migrations.AlterField(
            model_name='patient',
            name='CPF',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
