# Generated by Django 6.1.1 on 2026-09-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_rename_doctors_doctor_rename_pacients_pacient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10, verbose_name='Gênero'),
        ),
    ]
